/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : FTM0_PWM_CTL_Motor.h
**     Project     : ProcessorExpert
**     Processor   : MK60FX512VLQ15
**     Component   : TimerUnit_LDD
**     Version     : Component 01.164, Driver 01.11, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-07-15, 17:57, # CodeGen: 103
**     Abstract    :
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
**     Settings    :
**          Component name                                 : FTM0_PWM_CTL_Motor
**          Module name                                    : FTM0
**          Counter                                        : FTM0_CNT
**          Counter direction                              : Up
**          Counter width                                  : 16 bits
**          Value type                                     : uint16_t
**          Input clock source                             : Internal
**            Counter frequency                            : 4.6875 MHz
**          Counter restart                                : On-match
**            Period device                                : FTM0_MOD
**            Period                                       : 100 ?s
**            Interrupt                                    : Disabled
**          Channel list                                   : 4
**            Channel 0                                    : 
**              Mode                                       : Compare
**                Compare                                  : FTM0_C0V
**                Offset                                   : 99 ?s
**                Output on compare                        : Clear
**                  Output on overrun                      : Disconnect
**                  Initial state                          : Low
**                  Output pin                             : ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FBa_AD13/NFC_DATA10/I2S0_TXD0
**                  Output pin signal                      : PWM_CTL_L0Motor
**                Interrupt                                : Disabled
**            Channel 1                                    : 
**              Mode                                       : Compare
**                Compare                                  : FTM0_C1V
**                Offset                                   : 99 ?s
**                Output on compare                        : Clear
**                  Output on overrun                      : Disconnect
**                  Initial state                          : Low
**                  Output pin                             : ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FBa_AD12/NFC_DATA9/I2S0_TX_FS
**                  Output pin signal                      : PWM_CTL_L1Motor
**                Interrupt                                : Disabled
**            Channel 2                                    : 
**              Mode                                       : Compare
**                Compare                                  : FTM0_C2V
**                Offset                                   : 99 ?s
**                Output on compare                        : Clear
**                  Output on overrun                      : Disconnect
**                  Initial state                          : Low
**                  Output pin                             : CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUTa/I2S0_TX_BCLK
**                  Output pin signal                      : PWM_CTL_R2Motor
**                Interrupt                                : Disabled
**            Channel 3                                    : 
**              Mode                                       : Compare
**                Compare                                  : FTM0_C3V
**                Offset                                   : 99 ?s
**                Output on compare                        : Clear
**                  Output on overrun                      : Disconnect
**                  Initial state                          : Low
**                  Output pin                             : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FBa_AD11/NFC_DATA8/CMP1_OUT/I2S1_TX_BCLK
**                  Output pin signal                      : PWM_CTL_R3Motor
**                Interrupt                                : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnCounterRestart                           : Disabled
**              OnChannel0                                 : Disabled
**              OnChannel1                                 : Disabled
**              OnChannel2                                 : Disabled
**              OnChannel3                                 : Disabled
**              OnChannel4                                 : Disabled
**              OnChannel5                                 : Disabled
**              OnChannel6                                 : Disabled
**              OnChannel7                                 : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init               - LDD_TDeviceData* FTM0_PWM_CTL_Motor_Init(LDD_TUserData *UserDataPtr);
**         Enable             - LDD_TError FTM0_PWM_CTL_Motor_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable            - LDD_TError FTM0_PWM_CTL_Motor_Disable(LDD_TDeviceData *DeviceDataPtr);
**         SetPeriodTicks     - LDD_TError FTM0_PWM_CTL_Motor_SetPeriodTicks(LDD_TDeviceData *DeviceDataPtr,...
**         GetPeriodTicks     - LDD_TError FTM0_PWM_CTL_Motor_GetPeriodTicks(LDD_TDeviceData *DeviceDataPtr,...
**         SetOffsetTicks     - LDD_TError FTM0_PWM_CTL_Motor_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr,...
**         GetOffsetTicks     - LDD_TError FTM0_PWM_CTL_Motor_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr,...
**         GetCaptureValue    - LDD_TError FTM0_PWM_CTL_Motor_GetCaptureValue(LDD_TDeviceData *DeviceDataPtr,...
**         SelectOutputAction - LDD_TError FTM0_PWM_CTL_Motor_SelectOutputAction(LDD_TDeviceData...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FTM0_PWM_CTL_Motor.h
** @version 01.11
** @brief
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
*/         
/*!
**  @addtogroup FTM0_PWM_CTL_Motor_module FTM0_PWM_CTL_Motor module documentation
**  @{
*/         

#ifndef __FTM0_PWM_CTL_Motor_H
#define __FTM0_PWM_CTL_Motor_H

/* MODULE FTM0_PWM_CTL_Motor. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "FTM_PDD.h"
#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


#ifndef __BWUserType_FTM0_PWM_CTL_Motor_TValueType
#define __BWUserType_FTM0_PWM_CTL_Motor_TValueType
  typedef uint16_t FTM0_PWM_CTL_Motor_TValueType ; /* Type for data parameters of methods */
#endif
#define FTM0_PWM_CTL_Motor_CNT_INP_FREQ_U_0 0x0047868CUL /* Counter input frequency in Hz */
#define FTM0_PWM_CTL_Motor_CNT_INP_FREQ_R_0 4687507.324230194F /* Counter input frequency in Hz */
#define FTM0_PWM_CTL_Motor_CNT_INP_FREQ_COUNT 0U /* Count of predefined counter input frequencies */
#define FTM0_PWM_CTL_Motor_PERIOD_TICKS 0x01D5UL /* Initialization value of period in 'counter ticks' */
#define FTM0_PWM_CTL_Motor_NUMBER_OF_CHANNELS 0x04U /* Count of predefined channels */
#define FTM0_PWM_CTL_Motor_COUNTER_WIDTH 0x10U /* Counter width in bits  */
#define FTM0_PWM_CTL_Motor_COUNTER_DIR DIR_UP /* Direction of counting */
#define FTM0_PWM_CTL_Motor_OFFSET_0_TICKS 0x01D0ul /* Initialization value of offset as 'counter ticks' for channel 0 */
#define FTM0_PWM_CTL_Motor_OFFSET_1_TICKS 0x01D0ul /* Initialization value of offset as 'counter ticks' for channel 1 */
#define FTM0_PWM_CTL_Motor_OFFSET_2_TICKS 0x01D0ul /* Initialization value of offset as 'counter ticks' for channel 2 */
#define FTM0_PWM_CTL_Motor_OFFSET_3_TICKS 0x01D0ul /* Initialization value of offset as 'counter ticks' for channel 3 */
/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define FTM0_PWM_CTL_Motor_PRPH_BASE_ADDRESS  0x40038000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define FTM0_PWM_CTL_Motor_Init_METHOD_ENABLED /*!< Init method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_Enable_METHOD_ENABLED /*!< Enable method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_Disable_METHOD_ENABLED /*!< Disable method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_SetPeriodTicks_METHOD_ENABLED /*!< SetPeriodTicks method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_GetPeriodTicks_METHOD_ENABLED /*!< GetPeriodTicks method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_SetOffsetTicks_METHOD_ENABLED /*!< SetOffsetTicks method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_GetOffsetTicks_METHOD_ENABLED /*!< GetOffsetTicks method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_GetCaptureValue_METHOD_ENABLED /*!< GetCaptureValue method of the component FTM0_PWM_CTL_Motor is enabled (generated) */
#define FTM0_PWM_CTL_Motor_SelectOutputAction_METHOD_ENABLED /*!< SelectOutputAction method of the component FTM0_PWM_CTL_Motor is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */



/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_Init (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* FTM0_PWM_CTL_Motor_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_Enable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Enables the component - it starts the signal generation.
**         Events may be generated (see SetEventMask). The method is
**         not available if the counter can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_Disable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Disables the component - it stops signal generation and
**         events calling. The method is not available if the counter
**         can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_SetPeriodTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         The method sets timer re-initialization period (in timer
**         ticks). This method is available only if the property
**         ["Counter restart"] is switched to 'on-match' value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Ticks           - Number of counter ticks before counter
**                           re-initialization. Value 0 means maximal
**                           period value the same as "free-running
**                           mode", e.g. counter overflow or underflow
**                           without any explicit re-initialization.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_TICKS - Ticks parameter is out of
**                           possible range.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_SetPeriodTicks(LDD_TDeviceData *DeviceDataPtr, FTM0_PWM_CTL_Motor_TValueType Ticks);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_GetPeriodTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the number of counter ticks before re-initialization.
**         See also method [SetPeriodTicks]. This method is available
**         only if the property ["Counter restart"] is switched to
**         'on-match' value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         TicksPtr        - Pointer to return value of the
**                           number of counter ticks before
**                           re-initialization
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_GetPeriodTicks(LDD_TDeviceData *DeviceDataPtr, FTM0_PWM_CTL_Motor_TValueType *TicksPtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_SetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Sets the new offset value to channel specified by the
**         parameter ChannelIdx. It is user responsibility to use value
**         below selected period. This method is available when at
**         least one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         Ticks           - Number of counter ticks to compare
**                           match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel
**                           ERR_PARAM_TICKS - Ticks parameter is out of
**                           possible range.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, FTM0_PWM_CTL_Motor_TValueType Ticks);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_GetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the number of counter ticks to compare match channel
**         specified by the parameter ChannelIdx. See also method
**         [SetOffsetTicks]. This method is available when at least one
**         channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         TicksPtr        - Pointer to return value of the
**                           number of counter ticks to compare match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, FTM0_PWM_CTL_Motor_TValueType *TicksPtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_GetCaptureValue (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the content of capture register specified by the
**         parameter ChannelIdx. This method is available when at least
**         one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         ValuePtr        - Pointer to return value of the
**                           capture register.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range
**                           ERR_NOTAVAIL -  The capture mode is not
**                           selected for selected channel.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_GetCaptureValue(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, FTM0_PWM_CTL_Motor_TValueType *ValuePtr);

/*
** ===================================================================
**     Method      :  FTM0_PWM_CTL_Motor_SelectOutputAction (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Sets the type of compare match and counter overflow action
**         on channel output. This method is available when at least
**         one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         CompareAction   - Select output action
**                           on compare match
**     @param
**         CounterAction   - Select output action
**                           on counter overflow
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range
**                           ERR_NOTAVAIL -  Action is not possible on
**                           selected channel or counter. Supported
**                           combinations are HW specific.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError FTM0_PWM_CTL_Motor_SelectOutputAction(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, LDD_TimerUnit_TOutAction CompareAction, LDD_TimerUnit_TOutAction CounterAction);

/* END FTM0_PWM_CTL_Motor. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __FTM0_PWM_CTL_Motor_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
